name: Main Pipeline (Test & Tag)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Lint
    runs-on: macos-15
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Show toolchain
      run: |
        xcodebuild -version
        xcode-select -p
        swift --version
        swift package --version
    
    # We use our Makefile target which automatically installs swiftlint via Homebrew
    - name: Run Linter
      run: make lint

    - name: Build Application
      run: make build

    # Run unit tests and calculate test coverage using llvm-cov
    - name: Run Tests & Calculate Coverage
      run: make test-coverage

    - name: Report Code Coverage
      if: github.event_name == 'pull_request'
      uses: zgosalvez/github-actions-report-lcov@v4
      with:
        coverage-files: lcov.info
        minimum-coverage: 0
        github-token: ${{ secrets.GITHUB_TOKEN }}
        update-comment: true

    - name: Code Coverage Annotations
      if: github.event_name == 'pull_request'
      uses: ggilder/codecoverage@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COVERAGE_FILE_PATH: "lcov.info"
        COVERAGE_FORMAT: "lcov"

  release:
    name: Release
    needs: build-and-test
    runs-on: macos-15
    environment: release
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Semantic Release
      uses: cycjimmy/semantic-release-action@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GH_PAT || secrets.GITHUB_TOKEN }}
