name: Tag Pipeline (Build & Release)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    name: Build and Release Artifact
    runs-on: macos-15
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Extract Version
      id: get_version
      run: echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

    - name: Build and Package
      run: |
        chmod +x package.sh
        ./package.sh ${{ env.VERSION }}

    - name: Upload Release Asset
      uses: softprops/action-gh-release@v2
      with:
        files: ezlyrics-v${{ env.VERSION }}.dmg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
